rvm:
  - 2.2
  - 2.3
  - 2.4.4
  - 2.5.1
sudo: true
notifications:
  recipients:
    - activeldap@ml.commit-email.info
before_install:
  - travis/before_install.sh
before_script:
  - travis/before_script.sh
